apiVersion: batch/v1
kind: Job
metadata:
  name: stress-test-job
spec:
  template:
    spec:
      containers:
      - name: stress-container
        image: polinux/stress
        command:
        - stress
        - --cpu
        - "1"
        - --timeout
        - "60s"
      restartPolicy: Never
  backoffLimit: 4



