version: "3.9"

services:
  kubepulse-db:
    image: postgres:16
    container_name: kubepulse-db
    environment:
      POSTGRES_DB: kubepulse
      POSTGRES_USER: kubepulse
      POSTGRES_PASSWORD: kubepulse
    ports:
      - "5432:5432"
    volumes:
      - kubepulse-pgdata:/var/lib/postgresql/data

  kubepulse-redis:
    image: redis:7
    container_name: kubepulse-redis
    ports:
      - "6379:6379"

volumes:
  kubepulse-pgdata:
