apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepulse
  labels:
    app: kubepulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubepulse
  template:
    metadata:
      labels:
        app: kubepulse
    spec:
      containers:
        - name: kubepulse
          image: kubepulse:latest
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
