apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepulse
  labels:
    app: kubepulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubepulse
  template:
    metadata:
      labels:
        app: kubepulse
    spec:
      containers:
        - name: kubepulse
          image: kubepulse:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: kubepulse-config
            - secretRef:
                name: kubepulse-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
