from __future__ import annotations
from datetime import datetime, timedelta, timezone

def _build_report(
    scenario: str,
    pod_name: str,
    namespace: str,
    dry_run: bool,
) -> dict:
    started = datetime.now(timezone.utc)
    ended = started + timedelta(seconds=1)

    profiles = {
        "model_inference_timeout": {
            "success": False,
            "status": "fail",
            "recovery_window_seconds": 18.0,
            "latency_p50_ms": 420.0,
            "latency_p95_ms": 950.0,
            "latency_p99_ms": 1450.0,
            "error_rate": 0.06,
            "availability_achieved_pct_simulated": 94.0,
            "fallback_success_rate_pct": 72.0,
            "degraded_serving_mode": True,
            "full_outage": False,
            "user_visible_quality": "degraded",
            "ai_dependency": "model-inference",
            "ai_failure_mode": "timeout_spike",
            "recommendation": "Increase model timeout safeguards and fallback capacity.",
        },
        "vector_db_degraded_latency": {
            "success": True,
            "status": "pass",
            "recovery_window_seconds": 11.0,
            "latency_p50_ms": 240.0,
            "latency_p95_ms": 820.0,
            "latency_p99_ms": 1320.0,
            "error_rate": 0.015,
            "availability_achieved_pct_simulated": 99.0,
            "fallback_success_rate_pct": 88.0,
            "degraded_serving_mode": True,
            "full_outage": False,
            "user_visible_quality": "degraded",
            "ai_dependency": "vector-db",
            "ai_failure_mode": "degraded_latency",
            "recommendation": "Investigate vector index latency and retrieval fallback behavior.",
        },
        "embedding_service_unavailable": {
            "success": False,
            "status": "fail",
            "recovery_window_seconds": 16.0,
            "latency_p50_ms": 180.0,
            "latency_p95_ms": 540.0,
            "latency_p99_ms": 880.0,
            "error_rate": 0.12,
            "availability_achieved_pct_simulated": 0.0,
            "fallback_success_rate_pct": 0.0,
            "degraded_serving_mode": False,
            "full_outage": True,
            "user_visible_quality": "outage",
            "ai_dependency": "embedding-service",
            "ai_failure_mode": "dependency_unavailable",
            "recommendation": "Restore embedding service availability or enable cached embedding fallback.",
        },
        "tool_router_dependency_failure": {
            "success": False,
            "status": "fail",
            "recovery_window_seconds": 14.0,
            "latency_p50_ms": 260.0,
            "latency_p95_ms": 720.0,
            "latency_p99_ms": 1100.0,
            "error_rate": 0.08,
            "availability_achieved_pct_simulated": 92.0,
            "fallback_success_rate_pct": 45.0,
            "degraded_serving_mode": True,
            "full_outage": False,
            "user_visible_quality": "degraded",
            "ai_dependency": "tool-router",
            "ai_failure_mode": "dependency_failure",
            "recommendation": "Validate router dependency isolation and missing-tool fallback behavior.",
        },
        "partial_fallback_under_load": {
            "success": True,
            "status": "pass",
            "recovery_window_seconds": 20.0,
            "latency_p50_ms": 520.0,
            "latency_p95_ms": 1400.0,
            "latency_p99_ms": 1750.0,
            "error_rate": 0.03,
            "availability_achieved_pct_simulated": 97.0,
            "fallback_success_rate_pct": 81.0,
            "degraded_serving_mode": True,
            "full_outage": False,
            "user_visible_quality": "degraded",
            "ai_dependency": "fallback-path",
            "ai_failure_mode": "partial_fallback_under_load",
            "recommendation": "Increase fallback capacity and reduce degraded-mode latency under load.",
        },
    }

    p = profiles[scenario]

    return {
        "scenario": scenario,
        "pod_name": pod_name,
        "namespace": namespace,
        "started_at": started.isoformat(),
        "ended_at": ended.isoformat(),
        "success": p["success"],
        "recovery_window_seconds": p["recovery_window_seconds"],
        "restart_count": 0,
        "probe_mismatch": p["status"] == "fail" and p["degraded_serving_mode"],
        "status": p["status"],
        "latency_p50_ms": p["latency_p50_ms"],
        "latency_p95_ms": p["latency_p95_ms"],
        "latency_p99_ms": p["latency_p99_ms"],
        "error_rate": p["error_rate"],
        "baseline_latency_p50_ms": 120.0,
        "baseline_latency_p95_ms": 240.0,
        "baseline_latency_p99_ms": 400.0,
        "baseline_error_rate": 0.005,
        "observed_latency_p50_ms": p["latency_p50_ms"],
        "observed_latency_p95_ms": p["latency_p95_ms"],
        "observed_latency_p99_ms": p["latency_p99_ms"],
        "observed_error_rate": p["error_rate"],
        "latency_p50_drift_pct": round(((p["latency_p50_ms"] - 120.0) / 120.0) * 100, 2),
        "latency_p95_drift_pct": round(((p["latency_p95_ms"] - 240.0) / 240.0) * 100, 2),
        "latency_p99_drift_pct": round(((p["latency_p99_ms"] - 400.0) / 400.0) * 100, 2),
        "error_rate_delta": round(p["error_rate"] - 0.005, 4),
        "stdout": f"{'Dry run: simulated' if dry_run else 'Executed'} {scenario}",
        "stderr": "",
        "error": None,
        "readiness_before": "ready",
        "readiness_after": "ready" if p["degraded_serving_mode"] else "not-ready",
        "readiness_false_positive": p["degraded_serving_mode"],
        "pass_fail_reason": "AI-service reliability scenario evaluated against user-visible quality and SLO signals.",
        "recommendation": p["recommendation"],
        "availability_achieved_pct_simulated": p["availability_achieved_pct_simulated"],
        "fallback_success_rate_pct": p["fallback_success_rate_pct"],
        "degraded_serving_mode": p["degraded_serving_mode"],
        "full_outage": p["full_outage"],
        "user_visible_quality": p["user_visible_quality"],
        "ai_dependency": p["ai_dependency"],
        "ai_failure_mode": p["ai_failure_mode"],
    }

def run_ai_service_scenario(name: str, pod_name: str, namespace: str, dry_run: bool) -> dict:
    supported = {
        "model_inference_timeout",
        "vector_db_degraded_latency",
        "embedding_service_unavailable",
        "tool_router_dependency_failure",
        "partial_fallback_under_load",
    }
    if name not in supported:
        raise ValueError(f"Unsupported AI service scenario: {name}")
    return _build_report(name, pod_name, namespace, dry_run)
