apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-config
  namespace: argo-rollouts
data:
  metricProviderPlugins: |-
    - name: "kubepulse/network-regression"
      location: "file:///plugins/kubepulse-network-regression"
