apiVersion: argoproj.io/v1alpha1
kind: AnalysisRun
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"AnalysisRun","metadata":{"annotations":{},"name":"kubepulse-real-network-regression","namespace":"kubepulse-e2e"},"spec":{"metrics":[{"count":1,"failureLimit":0,"inconclusiveLimit":0,"name":"kubepulse-network-regression","provider":{"plugin":{"kubepulse/network-regression":{"canarySelector":"k8s:cohort=canary","hubbleRelay":"hubble-relay.kube-system.svc.cluster.local:80","maxLostEvents":0,"queryTimeoutSeconds":15,"stableSelector":"k8s:cohort=stable","thresholds":{"dnsFailureDelta":0.1,"dropRateDelta":0.1,"http5xxDelta":0.1,"minDNSQueries":1,"minFlows":20,"minHTTPRequests":1,"minTCPAttempts":10,"tcpFailureDelta":0.1},"windowSeconds":25}}}}]}}
  creationTimestamp: "2026-09-06T05:22:55Z"
  generation: 2
  name: kubepulse-real-network-regression
  namespace: kubepulse-e2e
  resourceVersion: "18399"
  uid: 74c445d7-f27e-47f8-949f-f298997bdee9
spec:
  metrics:
  - count: 1
    failureLimit: 0
    inconclusiveLimit: 0
    name: kubepulse-network-regression
    provider:
      plugin:
        kubepulse/network-regression:
          canarySelector: k8s:cohort=canary
          hubbleRelay: hubble-relay.kube-system.svc.cluster.local:80
          maxLostEvents: 0
          queryTimeoutSeconds: 15
          stableSelector: k8s:cohort=stable
          thresholds:
            dnsFailureDelta: 0.1
            dropRateDelta: 0.1
            http5xxDelta: 0.1
            minDNSQueries: 1
            minFlows: 20
            minHTTPRequests: 1
            minTCPAttempts: 10
            tcpFailureDelta: 0.1
          windowSeconds: 25
status:
  completedAt: "2026-09-06T05:22:58Z"
  dryRunSummary: {}
  message: 'Metric "kubepulse-network-regression" assessed Failed due to failed (1)
    > failureLimit (0): "Error Message: network regression detected: drop_rate"'
  metricResults:
  - count: 1
    failed: 1
    measurements:
    - finishedAt: "2026-09-06T05:22:58Z"
      message: 'network regression detected: drop_rate'
      metadata:
        canaryFlowEvents: "103"
        canaryLostEvents: "0"
        canarySelector: k8s:cohort=canary
        decision: FAIL
        evaluatedSignals: drop_rate,tcp_failure_rate
        hubbleRelay: hubble-relay.kube-system.svc.cluster.local:80
        provider: kubepulse/network-regression
        regressions: drop_rate
        stableFlowEvents: "831"
        stableLostEvents: "0"
        stableSelector: k8s:cohort=stable
        windowSeconds: "25"
      phase: Failed
      startedAt: "2026-09-06T05:22:57Z"
      value: '{"decision":"FAIL","stable":{"dnsFailureRate":0,"dropRate":0,"tcpFailureRate":0,"http5xxRate":0},"canary":{"dnsFailureRate":0,"dropRate":0.4854368932038835,"tcpFailureRate":0,"http5xxRate":0},"deltas":{"dnsFailureDelta":0,"dropRateDelta":0.4854368932038835,"tcpFailureDelta":0,"http5xxDelta":0},"evaluatedSignals":["drop_rate","tcp_failure_rate"],"regressions":["drop_rate"],"reasons":["network
        regression detected in 1 signal(s)"]}'
    message: 'network regression detected: drop_rate'
    metadata:
      analysis: stable-vs-canary-network-regression
      provider: kubepulse/network-regression
      telemetry: cilium-hubble
    name: kubepulse-network-regression
    phase: Failed
  phase: Failed
  runSummary:
    count: 1
    failed: 1
  startedAt: "2026-09-06T05:22:58Z"
